### ISSUE TITLE
eeui create eeui-demo就报错了..

### ISSUE THREAD

**Issue by shylon0719** [kuaifan/eeui#45]
$ eeui create eeui-demo
C:\Users\Administrator\AppData\Roaming\npm\node_modules\eeui-cli\lib\utils\index.js:260
        let matchs = content.match(/<dict>(.*?)<\/dict>/gs);
                                   ^

SyntaxError: Invalid regular expression flags
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:607:28)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\Administrator\AppData\Roaming\npm\node_modules\eeui-cli\cli.js:13:15)

**Comment by kang558** [comment]
估计是node版本太低

**Comment by kuaifan** [comment]
node版本太低
